<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */
$at_settings = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/footer');
$newsletterStyle = $at_settings['newsletter_style'];
$newsletterInputStyle = $at_settings['newsletter_input_underlined'];
$newsletterTitle = $at_settings['newsletter_title']; //__('Newsletter Sign Up')
$newsletterLabel = $at_settings['newsletter_label']; //__('Get the latest deals and more')
$newsletterLabelAria = $newsletterLabel ? $newsletterLabel : $newsletterTitle;
if ($newsletterInputStyle) {
    $newsletterInputStyle = 'inputs-style--underlined';
} else {
    $newsletterInputStyle = '';
}
?>
<div class="block newsletter newsletter-style--<?= $newsletterStyle ?> <?= $newsletterInputStyle ?>">
	<div class="block_newsletter_info">
		<?php if ($newsletterTitle) {
    ?>
			<div class="title"><?= $newsletterTitle ?></div> <?php
} ?>
		<?php if ($newsletterLabel) {
        ?><label class="label">
			<span><?= $block->escapeHtml($newsletterLabel) ?></span></label> <?php
    } ?>

    <div class="content">
		<form class="form subscribe"
			  novalidate
			  action=""
			  method="post"
			  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
			  id="newsletter-validate-detail">
			<div class="field newsletter">
				<div class="control">
					<label for="newsletter">
						<span class="label">
							<?= $block->escapeHtml($newsletterLabelAria) ?>
						</span>
					</label>
					<!-- <input name="email" type="email" id="newsletter"
						   placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
						   data-validate="{required:true, 'validate-email':true}"
					/>	 -->
				</div>
			</div>
			<div class="actions">
				<button class="button-custom"
						title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
						type="button"
						aria-label="Subscribe" onClick="location.href='https://guinnesswebstore.us11.list-manage.com/subscribe?u=10a348d53609b2f3628985330&id=8332f91a01'">
					<?= $block->escapeHtml(__('Subscribe')) ?>
				</button>
			</div>
		</form>
	</div>
	</div>
	
</div>
