<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
$_product = $block->getProduct();
$actions_position = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/product/actions_position');
if($_product->getAttributeSetId() != 9){
	if ( '2' == $actions_position ) {
	?>
	<div class="product-addto-links" data-role="add-to-links">
	    <?= $block->getChildHtml() ?>
	</div>
	<?php } ?>
<?php } ?>