<?php

use Magento\Catalog\Block\Product\ReviewRendererInterface;

/** @var \Mirasvit\Related\Block\Block $block */
$products = $block->getProducts();

if (count($products) == 0) {
    return;
}

$showCart     = true;
$showWishlist = false;
$showCompare  = false;
?>

<div class="mst-related__block-bulletproof">
    <div class="bulletproof-title"><?= $block->getTitle() ?></div>

    <div class="bulletproof-content">
        <ol class="bulletproof-items">
            <?php foreach ($products as $product) : ?>
                <li class="bulletproof-item">
                    <div class="bulletproof-item-info">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>" class="bulletproof-item-photo">
                            <img
                                    src="<?= $block->getImage($product, 'product_base_image')->getImageUrl() ?>"
                                    alt="<?= $block->escapeHtml($product->getName()) ?>"
                                    width="152"
                                    height="190"/>
                        </a>

                        <div class="bulletproof-item-details">
                            <strong class="bulletproof-item-name">
                                <a class="bulletproof-item-link" title="<?= $block->escapeHtml($product->getName()) ?>" href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>">
                                    <?= $block->escapeHtml($product->getName()) ?>
                                </a>
                            </strong>

                            <?= $block->getProductPrice($product) ?>

                            <?php if ($showCart) : ?>
                                <div class="bulletproof-item-actions">
                                    <?php if ($showCart) : ?>
                                        <div class="actions-primary">
                                            <?php if ($product->isSaleable()) : ?>
                                                <?php if ($product->getTypeInstance()->hasRequiredOptions($product)) : ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($product)) ?>"}}' type="button"
                                                            title="<?= $block->escapeHtmlForAttr(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                <?php else : ?>
                                                    <?php
                                                    $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                    $postData       = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($product)), ['product' => $product->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary" data-post='<?= $postData ?>'
                                                            type="button" title="<?= $block->escapeHtmlForAttr(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else : ?>
                                                <?php if ($product->getIsSalable()) : ?>
                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else : ?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif ?>
                                </div>
                            <?php endif ?>

                            <?php if ($showWishlist || $showCompare) : ?>
                                <div class="actions-secondary" data-role="add-to-links">

                                    <?php if ($showWishlist && $this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                        <a href="#" data-post='<?= $block->getAddToWishlistParams($product) ?>'
                                           class="action"
                                           data-action="add-to-wishlist towishlist"
                                           title="<?= $block->escapeHtml(__('Add to Wish List')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    <?php endif; ?>

                                    <?php if ($showCompare && $block->getAddToCompareUrl()) : ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare') ?>
                                        <a href="#" class="action tocompare"
                                           data-post='<?= $compareHelper->getPostDataParams($product) ?>'
                                           title="<?= $block->escapeHtml(__('Add to Compare')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ol>
    </div>
</div>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Mirasvit_Related::css/source/module/block/_bulletproof.css') ?>"/>
